name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        arch:
          - arm
          - arm64
          - amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
         fetch-depth: 0
      - name: Setup golang
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          go-version: '^1.20'
      - name: Check go version
        run: go version
      - name: Build
        run: |
          go build -buildmode exe -o dist/nomad-operator-linux-${{ matrix.arch }} .
          ls -lht dist
          file dist/*
        env:
          GOARCH: ${{ matrix.arch }}
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: nomad-operator-linux-${{ matrix.arch }}
          path: dist/nomad-operator-linux-${{ matrix.arch }}
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download math result for job 1
        uses: actions/download-artifact@v5
      - name: What did we get?
        run: ls -lht *
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
